import random
import subprocess
import numpy as np
import os
from multiprocessing import Pool

import PATH
from data_processing.DIS_dataset import DIS_dataset
#generate a new dataset by applying IAD data to a dataset generated by the MCML
np.random.seed(42)
random.seed(42)

dataset = DIS_dataset(data_folder="MCML_property_space_rectangle")

def run_iad(sample_file):
    SAMPLE = sample_file
    print(sample_file)

    SAVE_PATH = PATH.PROCESSED_PATH + SAMPLE

    if os.path.exists(SAVE_PATH):
        if os.path.isfile(SAVE_PATH + "/1.rxt") and os.path.isfile(SAVE_PATH + "/1.txt"):
            print(f"\t [INFO] Already computed SAVE_PATH:  {SAVE_PATH}")
            return

    SAVE_FILE_NAME = "1.rxt"

    STANDARD_REFLECTANCE = 0.985
    REFRACTIVE_INDEX_SAMPLE = 1.43
    REFRACTIVE_INDEX_GLASS = 0.0
    THICKNESS_GLASS = 0.0
    BEAM_DIAMETER = 8.0
    WALL_REFLECTANCE = 0.985
    DETECTOR_REFLECTANCE = 0.0
    SPHERE_DIAMETER = 50.0
    SAMPLE_PORT_DIAMETER = 9.9
    ENTRANCE_PORT_DIAMETER = 4.9
    DETECTOR_PORT_DIAMETER = 0.2
    SPHERE_DIAMETER_2 = 50.0
    SAMPLE_PORT_DIAMETER_2 = 9.9
    ENTRANCE_PORT_DIAMETER_2 = 0.0
    DETECTOR_PORT_DIAMETER_2 = 0.2

    if not os.path.exists(SAVE_PATH):
        os.makedirs(SAVE_PATH)
  #  seed = int.from_bytes(bytes(sample_file, "UTF-8"), byteorder="big") % 2**32
    seed = int(sample_file.split(".")[1])
    print("seed: ", str(sample_file))
    np.random.seed(seed)
    random.seed(seed)
    THICKNESS_SAMPLE = 3.0 #2 + 2 * np.random.random()
    print("Calculated thickness from file: ", THICKNESS_SAMPLE, "mm")

    R_wl = np.ones(len(dataset))*600.0
    total_reflectance = dataset.data["M_R"]
    total_transmission = dataset.data["M_T"]

    with open(SAVE_PATH + SAVE_FILE_NAME, "w") as rxt_file:
        rxt_file.writelines(f"IAD1 {REFRACTIVE_INDEX_SAMPLE:.6f}"
                            f"\t{REFRACTIVE_INDEX_GLASS:.6f}"
                            f"\t{THICKNESS_SAMPLE:.6f}"
                            f"\t{THICKNESS_GLASS:.6f}"
                            f"\t{BEAM_DIAMETER:.6f}"
                            f"\t{STANDARD_REFLECTANCE:.6f}"
                            f"\t0.000000"
                            f"\t{SPHERE_DIAMETER:.6f}"
                            f"\t{SAMPLE_PORT_DIAMETER:.6f}"
                            f"\t{ENTRANCE_PORT_DIAMETER:.6f}"
                            f"\t{DETECTOR_PORT_DIAMETER:.6f}"
                            f"\t{WALL_REFLECTANCE:.6f}"
                            f"\t{SPHERE_DIAMETER_2:.6f}"
                            f"\t{SAMPLE_PORT_DIAMETER_2:.6f}"
                            f"\t{ENTRANCE_PORT_DIAMETER_2:.6f}"
                            f"\t{DETECTOR_PORT_DIAMETER_2:.6f}"
                            f"\t{WALL_REFLECTANCE:.6f}"
                            f"\t2.000000\n")
        for wl_idx, wl in enumerate(R_wl):
            rxt_file.writelines(f"{wl:.6f} {total_reflectance[wl_idx]:.6f} {total_transmission[wl_idx]:.6f}\n")

    print("Starting IAD program")
    cmd = list()
    cmd.append(PATH.IAD_PATH)
    cmd.append("-q 12")
    cmd.append("-i 8")
    cmd.append("-g 0.7")
    cmd.append(SAVE_PATH + "1.rxt")
    subprocess.run(cmd)


if __name__ == "__main__":
    os.chdir("../")
    samples = []
    for n in range(1):
        samples.append(f"/IAD_MCML_data_reverse/T.{n}.{n}.a/1/")

    with Pool(19) as p:
        p.map(run_iad, samples)
